### ISSUE TITLE
Добавление веса дерева

### ISSUE THREAD

**Issue by Kirollbas** [AnjeZenda/Kruskal_Algorithm#42]
Добавить отображение веса текущего графа по ходу работы алгоритма Краскала.

**Comment by AnjeZenda** [comment]
Не работает отображение веса при переходах вида `next step` ... `prev step` ... `next step`
![image](https://github.com/AnjeZenda/Kruskal_Algorithm/assets/80576026/457eec8d-42f5-4e6e-8ae8-60143d6ff97c)
проблема где-то в этом месте
